### ISSUE TITLE
e4 keys expired, consumet api down

### ISSUE THREAD

**Issue by ks3rr** [eatmynerds/key#1]
Hello, it appears that the e4 keys have expired, and the consumet API for FlixHQ is not functioning. Please check. Thank you.

**Comment by eatmynerds** [comment]
Seems to be working for me
![Screenshot 2024-02-23 153128](https://github.com/eatmynerds/key/assets/153967995/b4c253d8-6c03-4435-9a59-a4957017eab6)
What is it saying on your end?

**Comment by ks3rr** [comment]
It says this:
{"message":"Something went wrong. Please try again later."}
This repo is being referred in consumet.ts library in vidcloud extractor. And it gives this error. Recently a commit was done on it, to change from keys4.fun to this key repo. But both keys4.fun and the latest repo referring this key.tx is not working.

**Comment by eatmynerds** [comment]
The reason is that the urls aren't being encrypted anymore. This might change in the future but for now they aren't
